# -*- coding: utf-8 -*-
"""facial_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Pj07tKOchCrs1V6MUAbD4FdPaQToWYe
"""

!pip install google-colab

from google.colab.patches import cv2_imshow

# prompt: code for facial recognition

!pip install mtcnn
import cv2
import numpy as np
from mtcnn.mtcnn import MTCNN

# Load the image
image = cv2.imread('/content/fake_image.jpg')

# Create a detector
detector = MTCNN()

# Detect faces in the image
faces = detector.detect_faces(image)

# Print the number of faces detected
print(f'Number of faces detected: {len(faces)}')

# Loop over the faces detected
for face in faces:
    # Get the bounding box of the face
    x, y, width, height = face['box']

    # Draw a rectangle around the face
    cv2.rectangle(image, (x, y), (x + width, y + height), (0, 255, 0), 2)

# Display the image
cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()